---
api:
  user: "hetzner-api-user"
  password: "hetzner-api-password"
failover_ip: "0.0.0.0"
server:
  - "1.2.3.4"
  - "4.5.6.7"
notification_mail_to:
  - info@example.com
database:
  driver: "pg"
  user: "postgres-user"
  password: "postgres-password"
  port: "5432"
  name: "postgres-database-name"
  trigger_file: /var/lib/postgresql/10/main/trigger.file
ssh_user: "ssh-user"
smtp:
  server: "smtp.example.com"
  username: "smtp-user"
  password: "smtp-password"
  port: 465
  starttls: true
  sender: "smtp-info@example.org"